export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Buddy the Golden",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Princess Pink",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "DUCHESS",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Franklin P.",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Shiloh the Siberian Husky",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Charlie",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Cilantro & Pina",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Scout",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Spudz McKenzie III",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Max",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Golden meetup last week. Try and spot me!",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 12,
    comment: 1,
  },
  {
    id: 2,
    desc: "Me competing at Wimbledon. Hard work pays off!",
    photo: "assets/post/2.jpeg",
    date: "30 mins ago",
    userId: 2,
    like: 122,
    comment: 17,
  },
  {
    id: 3,
    desc: "Fresh from the groomer, who this?",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 41,
    comment: 3,
  },
  {
    id: 4,
    desc: "All you need in life's a good ball.",
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 17,
    comment: 5,
  },
  {
    id: 5,
    desc: "birthday squad before we roll out to the run",
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 123,
    comment: 55,
  },
  {
    id: 6,
    desc: "when your human is a master chef with a small stomach",
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 54,
    comment: 16,
  },
  {
    id: 7,
    desc: "First day back at the park!",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 39,
    comment: 3,
  },
  {
    id: 8,
    desc: "Dog Days",
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 10,
    comment: 2,
  },
  {
    id: 9,
    desc: "Live every day like it was week.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 191,
    comment: 30,
  },
  {
    id: 10,
    desc: "mom caught me snoozin' lol",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 54,
    comment: 10,
  },
];
